### PR TITLE
Us1 activity

### PR DESCRIPTION
**Pull request by FLorianBlm**
html section activity

### CODE REVIEW

**Review by thocle86 — DISMISSED** [review]
ok

**Review by thocle86 — COMMENTED** [review]
Use <figure> and <figcaption> with

**Review by thocle86 — DISMISSED** [review]
ok

**Review by Quentin-BLANC — DISMISSED** [review]

**Review by Quentin-BLANC — APPROVED** [review]

**Review by thocle86 — APPROVED** [review]
ok

**Review by RomainClair — APPROVED** [review]

**Pull request merged**
